# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://nannxiao.github.io/
baseurl: /sustain/
title: Nan Xiao
author: Nan Xiao
description: Personal blog and resume
avatar: profile.png
email: nanxiao@uw.edu
github: nannxiao # username
twitter: username
linkedin: nan-xiao
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
